# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://calabruix.es/"
locale = "en"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[permalinks]
  [permalink.posts]
    posts = "/:sections/:slugorfilename"

[languages]
  [languages.en]
    locale = "en"
    label = "English"
    weight = 1
    title = "Calabruix"
    contentDir = "content/en"

  [languages.en.params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2 January 2006"
    # logo = "img/calabruix-logo-512x512.webp"
    logo = "img/hail-icon.svg"
    # Secondary logo for the mode not selected in defaultAppearance
    # secondaryLogo = "img/secondary-logo.png"
    description = "My blog about systems engineering and technology"
    # copyright = "Copy, _right?_ :thinking_face:"

  [languages.en.params.author]
    name = "Jaume Sabater"
  # email = "jsabater@gmail.com"
    image = "img/jsabater.jpg"
  # imageQuality = 96
    headline = "Ubi sapientas ibi libertas"
    bio = "CTO and systems engineer"
    links = []

  [languages.ca]
    locale = "ca"
    label = "Catalan"
    weight = 2
    title = "Calabruix"
    contentDir = "content/ca"

  [languages.ca.params]
    displayName = "CA"
    isoCode = "ca"
    rtl = false
    dateFormat = "2 de gener de 2006"
    logo = "img/hail-icon.svg"
    # Secondary logo for the mode not selected in defaultAppearance
    # secondaryLogo = "img/secondary-logo.png"
    description = "El meu blog sobre enginyeria de sistemes i tecnologia"
    # copyright = "Copy, _right?_ :thinking_face:"

  [languages.ca.params.author]
    name = "Jaume Sabater"
  # email = "jsabater@gmail.com"
    image = "img/jsabater.jpg"
  # imageQuality = 96
    headline = "Ubi sapientas ibi libertas"
    bio = "CTO i enginyer de sistemes"
    links = []
